name: r0sa_profile
description: r0saのポートフォリオサイト

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.11
  scrollable_positioned_list: ^0.3.8


  # 状態管理
  flutter_riverpod: ^2.3.6
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/cat.png
    - assets/record.png
    - assets/rectangle.png
    - assets/r0sa.png
    - assets/mathematics.png

